export interface CountryDetailed { 
    "country-name": string,
    "iso2": string,
    "iso3": string,
    "top-level-domain": string,
    "fips": string,
    "iso-numeric": string,
    "geonameid": string,
    "e164": string,
    "phone-code": string,
    "continent": string,
    "capital": string,
    "time-zone-in-capital": string,
    "currency": string,
    "language-codes": string,
    "languages": string,
    "area-km2": string,
    "internet-hosts": string,
    "internet-users": string,
    "phones-mobile": string,
    "phones-landline": string,
    "gdp": string,
}
